// Treinador Adjunto — every deterministic DM text, in PT-PT, PT-BR and EN.
// No model is involved in any of these: numbers in them come from code.
// lang: "pt" | "ptbr" | "en" (a group's "pt+en" speaks PT-PT in DMs, plan §2).

export const LANGS = ["pt", "ptbr", "en"];
export const dmLang = (linkLang, groupLang) =>
  LANGS.includes(linkLang) ? linkLang : groupLang === "en" ? "en" : groupLang === "ptbr" ? "ptbr" : "pt";

export const NAME = { pt: "Treinador Adjunto", ptbr: "Auxiliar Técnico", en: "Assistant Coach" };
export const SHORT = { pt: "o Adjunto", ptbr: "o Auxiliar", en: "Coach" };

const list = (xs) => xs.join(", ");

const PT = {
  welcome: ({ nick, group, formatDesc, others }) => [
    `🧢 Olá ${nick}! Sou o teu *${NAME.pt}* no ${group}.`,
    "A partir de agora trato dos bastidores contigo, aqui em privado:",
    "• *Fechar o jogo* — aviso-te quando faltar gente e, se quiseres, mando o lembrete ao grupo ou abro vagas.",
    "• *Equipas* — 24h antes do jogo proponho equipas equilibradas (com OVR e química de quem joga junto) para aprovares antes de saírem.",
    "• *Matchday* — faço a tabela da noite no formato do vosso jogo e mando-te o resumo no fim.",
    "Nada vai para o grupo sem o teu \"sim\". E podes perguntar-me o que quiseres: \"quem devia ir à baliza?\", \"muda o jogo para sexta às 21h\"…",
    ...(others?.length ? [`Também és organizador do ${list(others)}. Estou agora focado no *${group}* — para mudar escreve *grupo <nome>*.`] : []),
    formatDesc
      ? `O vosso formato atual é: ${formatDesc}. Queres mudar alguma coisa? (escreve *formato* para mudar)`
      : "Para começar: *como é o formato do vosso jogo?*\n1️⃣ Avulso — jogos soltos, sem tabela\n2️⃣ Campeonato — pontos por vitória/empate/derrota, tabela da noite (recomeça todas as semanas)\n3️⃣ Personalizado — defines tudo (equipas, sistema de jogos, play-off…)",
  ].join("\n"),
  notFound: "Não encontrei nenhum grupo onde sejas organizador com este número. Confirma o teu telemóvel no Perfil da app (com indicativo) ou usa o botão «Ativar o Treinador Adjunto» nas definições do grupo.",
  codeInvalid: "Este código já não é válido. Gera um novo na app PITCH → Grupo → Definições.",
  chooseGroup: (names) => `És organizador de vários grupos:\n${names.map((n, i) => `${i + 1}) ${n}`).join("\n")}\n\nQual queres ativar? Responde com o número.`,
  chooseGroupAgain: (n) => `Responde com o número (1 a ${n}) ou o nome do grupo.`,
  switched: (g) => `👍 Agora estou focado no *${g}*.`,
  unknownGroup: (names) => `Não encontrei esse grupo. Os teus grupos: ${list(names)}.`,
  help: "Comandos rápidos: *estado* · *tabela* · *equipas* · *formato* · *grupo <nome>* · *pausa* / *retoma* · *sim* / *não* para propostas. Para o resto, escreve à vontade.",
  paused: "⏸️ Ok, paro as mensagens automáticas. Escreve *retoma* quando quiseres.",
  resumed: "▶️ Voltei às mensagens automáticas.",
  langSet: "👍 Combinado.",
  nothingPending: "Não há nada à espera da tua confirmação.",
  expired: (id) => `A proposta #${id} já expirou.`,
  rejected: (id) => `Ok, esqueci a proposta #${id}.`,
  failedState: "As coisas mudaram entretanto (jogo, hora ou equipas) — não fiz nada. Diz-me de novo o que queres.",
  dryRun: "(modo de teste: não alterei nada)",
  degraded: (link) => `Hoje já pensei muito 😅 — até amanhã respondo só a comandos: *estado*, *tabela*, *equipas*, *sim/não*. O resto faz-se na app: ${link}`,
  refusal: "Não consigo ajudar com isso.",
  continuePrompt: "Diz-me se queres que continue.",
  error: "Tive um problema a tratar disso. Tenta outra vez daqui a pouco.",
  noGame: "Não há nenhum jogo marcado agora.",
  guardFallback: "Prefiro não arriscar números que não confirmei. Isto é o que os dados dizem:",
  notManager: "Já não és organizador deste grupo, por isso não posso fazer isso.",
  // format onboarding
  ob: {
    type: "Como é o formato do vosso jogo?\n1️⃣ Avulso — jogos soltos, sem tabela\n2️⃣ Campeonato — tabela da noite (recomeça todas as semanas)\n3️⃣ Personalizado — defines tudo",
    teams: "Quantas equipas por noite? (2 a 6 · normalmente 2)",
    playersPerTeam: "Quantos jogadores por equipa? (normalmente 5)",
    schedule: "Como se organizam os jogos?\n1️⃣ Todos contra todos\n2️⃣ Quem ganha fica\n3️⃣ Número fixo de jogos\n4️⃣ Vamos marcando",
    legs: "Todos contra todos:\n1️⃣ uma volta\n2️⃣ ida e volta",
    winnerStays: "Quem ganha fica: no máximo quantos jogos seguidos em campo? (normalmente 2)",
    fixedGames: "Quantos jogos por noite?",
    gameMinutes: "Quantos minutos tem cada jogo? (normalmente 10)",
    goalCap: "Há limite de golos? (ex.: 2 = quem marcar 2 ganha · 0 = sem limite)",
    points: "Pontos por vitória/empate/derrota? (normalmente 3/1/0)",
    tiebreakers: "Desempate depois dos pontos? Proponho: diferença de golos, golos marcados, confronto direto (responde *ok*).\nOu escolhe a ordem: 1 DG · 2 GM · 3 confronto direto · 4 vitórias · 5 menos golos sofridos · 6 sorteio (ex.: \"3 1 2\")",
    playoffs: "Fase final?\n1️⃣ Sem play-off\n2️⃣ Final entre os 2 primeiros\n3️⃣ Meias-finais entre os 4 primeiros\n4️⃣ 1.º vai direto à final (play-off entre os 3)",
    thirdPlace: "Jogo de 3.º/4.º lugar? (sim/não)",
    penalties: "Empate no play-off decide-se a penáltis? (sim/não)",
    summary: (desc) => `${desc}\nGuardo assim? (sim/não)`,
    invalid: "Não percebi. ",
    hintExit: " (escreve *sair* para continuar depois ou *recomeçar*)",
    saved: (desc) => `✅ Formato guardado: ${desc}\nA app já usa este formato no Matchday.`,
    restart: "Ok, vamos recomeçar.",
    cancelled: "Ok, fica para depois. Escreve *formato* quando quiseres continuar.",
  },
  // teams
  teams: {
    header: (c, s) => c >= s ? `⚽ Jogo fechado (${c}/${s})! Proposta de equipas:` : `⚽ Proposta de equipas (${c}/${s} confirmados):`,
    appDraft: "📝 Esta é a versão que está na app:",
    footer: "Responde *ok* para confirmar, *troca X com Y*, *separa X e Y* ou *sorteia de novo*.",
    shortAsk: (c, s, when) => `⚽ Jogo ${when}: ${c}/${s} confirmados. Proponho equipas com os ${c} confirmados ou espero? (*propõe* / *espera*)`,
    waiting: "Ok, espero. Mando a proposta quando o jogo fechar.",
    together: (a, b, w, g) => `💡 ${a} e ${b} juntos ganharam ${w} de ${g} jogos — talvez separá-los?`,
    hot: (n) => `🔥 ${n} está em forma`,
    gkMissing: (t) => `🧤 ${t} não tem guarda-redes`,
    spread: (s) => `⚖️ Diferença de OVR entre equipas: ${s}`,
    approved: "✅ Equipas confirmadas — já aparecem na app.",
    askPublish: "Publico as equipas no grupo? (sim/não)",
    published: "✅ Publicado no grupo.",
    notPublished: "Ok, não publico.",
    byOther: (nick) => `✅ O ${nick} já aprovou as equipas — está tudo tratado.`,
    confirmedInApp: "✅ As equipas já foram confirmadas na app.",
    changedInApp: "Mexeste nas equipas na app entretanto — mandei-te a versão da app para validares.",
    diff: (out, inn) => `🔄 ${out.length ? `Saiu ${list(out)}` : ""}${out.length && inn.length ? " e " : ""}${inn.length ? `entrou ${list(inn)}` : ""} — ajusto as equipas? (sim/não)`,
    unknownPlayer: (r) => `Não encontrei "${r}" nas equipas.`,
    ambiguous: (r, opts) => `"${r}" pode ser ${list(opts)}. Qual?`,
    gameLocked: "O jogo já começou ou fechou — já não mexo nas equipas.",
  },
  group: {
    quiet: "Agora é hora de silêncio no grupo (23h–8h). Tenta de manhã.",
    noBot: "O bot não está no grupo do WhatsApp deste grupo, por isso não consigo publicar lá.",
    sent: "✅ Enviado no grupo.",
    already: "Isso já foi enviado no grupo.",
  },
  done: (what) => `✅ Feito: ${what}.`,
  // proactive (templated, zero LLM)
  p: {
    status: ({ when, venue, c, s, pending, late, menu = true }) => [
      `📋 Ponto de situação — ${when}${venue ? ` (${venue})` : ""}`,
      `✅ ${c}/${s} confirmados · faltam *${s - c}*`,
      ...(pending.length ? [`⏳ Ainda sem resposta: ${list(pending)}`] : []),
      ...(late ? [late] : []),
      ...(menu ? ["Queres que eu:\n1️⃣ mande já um lembrete no grupo com os nomes de quem falta\n2️⃣ abra vagas a avulsos (partilho o link de convite)"] : []),
    ].join("\n"),
    lateLine: (rows) => `🐢 Costumam confirmar tarde: ${rows.map((r) => `${r.nick} (~${r.h}h antes)`).join(", ")}`,
    lateLearning: "🐢 Ainda estou a aprender quem confirma tarde.",
    reminderHint: ({ c, s, at }) => `⏰ Faltam ${s - c} para o jogo. O lembrete automático sai no grupo às ${at}.\nQueres que mande já um mais forte, com os nomes de quem falta? (*1*)`,
    gameday: ({ c, s }) => `📅 Dia de jogo e ainda faltam ${s - c} (${c}/${s}).\n1️⃣ abrir vagas a avulsos\n2️⃣ reduzir as vagas para ${c}\n3️⃣ cancelar o jogo`,
    spot: ({ nick, c, s }) => `🔓 ${nick ? `O ${nick} saiu` : "Abriu uma vaga"} — faltam ${s - c} (${c}/${s}) e não há lista de espera.\n1️⃣ abrir vagas a avulsos\n2️⃣ mandar lembrete no grupo`,
    groupStage: ({ table, semis }) => `📊 Fase de grupos terminada:\n${table}${semis ? `\n🥊 ${semis}` : ""}`,
    summary: ({ header, table, final, top }) => [header, table, final, top, "A votação MVP está aberta na app."].filter(Boolean).join("\n"),
    unfinished: (link) => `⏱️ O dia de jogo ainda está aberto na app. Esqueceste-te de o terminar? ${link}`,
    formatNudge: "📐 Ainda não definimos o formato do vosso jogo. Escreve *formato* e trato disso em 1 minuto.",
    prefix: (g) => `[${g}] `,
  },
};

const PTBR = {
  ...PT,
  welcome: ({ nick, group, formatDesc, others }) => [
    `🧢 Oi ${nick}! Sou o seu *${NAME.ptbr}* no ${group}.`,
    "A partir de agora cuido dos bastidores com você, aqui no privado:",
    "• *Fechar o jogo* — aviso quando faltar gente e, se quiser, mando o lembrete no grupo ou abro vagas.",
    "• *Times* — 24h antes do jogo proponho times equilibrados (com OVR e entrosamento) para você aprovar antes de saírem.",
    "• *Matchday* — faço a tabela da noite no formato de vocês e mando o resumo no fim.",
    "Nada vai para o grupo sem o seu \"sim\". E pode me perguntar o que quiser: \"quem devia ir pro gol?\", \"muda o jogo pra sexta às 21h\"…",
    ...(others?.length ? [`Você também organiza ${list(others)}. Agora estou focado no *${group}* — para trocar escreva *grupo <nome>*.`] : []),
    formatDesc
      ? `O formato atual de vocês é: ${formatDesc}. Quer mudar alguma coisa? (escreva *formato*)`
      : "Para começar: *qual é o formato do jogo de vocês?*\n1️⃣ Avulso — jogos soltos, sem tabela\n2️⃣ Campeonato — pontos por vitória/empate/derrota, tabela da noite (recomeça toda semana)\n3️⃣ Personalizado — você define tudo",
  ].join("\n"),
  notFound: "Não encontrei nenhum grupo onde você seja organizador com este número. Confira seu celular no Perfil do app (com DDI) ou use o botão «Ativar o Auxiliar Técnico» nas configurações do grupo.",
  codeInvalid: "Este código não vale mais. Gere um novo no app PITCH → Grupo → Configurações.",
  chooseGroup: (names) => `Você organiza vários grupos:\n${names.map((n, i) => `${i + 1}) ${n}`).join("\n")}\n\nQual quer ativar? Responda com o número.`,
  chooseGroupAgain: (n) => `Responda com o número (1 a ${n}) ou o nome do grupo.`,
  switched: (g) => `👍 Agora estou focado no *${g}*.`,
  help: "Comandos rápidos: *estado* · *tabela* · *times* · *formato* · *grupo <nome>* · *pausa* / *retoma* · *sim* / *não* para propostas. Para o resto, escreva à vontade.",
  paused: "⏸️ Beleza, paro as mensagens automáticas. Escreva *retoma* quando quiser.",
  degraded: (link) => `Hoje já pensei demais 😅 — até amanhã respondo só comandos: *estado*, *tabela*, *times*, *sim/não*. O resto é no app: ${link}`,
  ob: {
    ...PT.ob,
    type: "Qual é o formato do jogo de vocês?\n1️⃣ Avulso — jogos soltos, sem tabela\n2️⃣ Campeonato — tabela da noite (recomeça toda semana)\n3️⃣ Personalizado — você define tudo",
    teams: "Quantos times por noite? (2 a 6 · normalmente 2)",
    playersPerTeam: "Quantos jogadores por time? (normalmente 5)",
    winnerStays: "Quem ganha fica: no máximo quantos jogos seguidos? (normalmente 2)",
    goalCap: "Tem limite de gols? (ex.: 2 = quem fizer 2 ganha · 0 = sem limite)",
    tiebreakers: "Desempate depois dos pontos? Proponho: saldo de gols, gols pró, confronto direto (responda *ok*).\nOu escolha a ordem: 1 SG · 2 GP · 3 confronto direto · 4 vitórias · 5 menos gols sofridos · 6 sorteio (ex.: \"3 1 2\")",
    playoffs: "Mata-mata?\n1️⃣ Sem mata-mata\n2️⃣ Final entre os 2 primeiros\n3️⃣ Semifinais entre os 4 primeiros\n4️⃣ 1º direto na final (mata-mata entre os 3)",
    penalties: "Empate no mata-mata vai para os pênaltis? (sim/não)",
    hintExit: " (escreva *sair* para continuar depois ou *recomeçar*)",
    saved: (desc) => `✅ Formato salvo: ${desc}\nO app já usa este formato no Matchday.`,
    restart: "Beleza, vamos recomeçar.",
    cancelled: "Beleza, fica pra depois. Escreva *formato* quando quiser continuar.",
  },
  teams: {
    ...PT.teams,
    header: (c, s) => c >= s ? `⚽ Rachão fechado (${c}/${s})! Proposta de times:` : `⚽ Proposta de times (${c}/${s} confirmados):`,
    appDraft: "📝 Esta é a versão que está no app:",
    footer: "Responda *ok* para confirmar, *troca X com Y*, *separa X e Y* ou *sorteia de novo*.",
    shortAsk: (c, s, when) => `⚽ Jogo ${when}: ${c}/${s} confirmados. Proponho times com os ${c} confirmados ou espero? (*propõe* / *espera*)`,
    together: (a, b, w, g) => `💡 ${a} e ${b} juntos ganharam ${w} de ${g} jogos — melhor separar?`,
    gkMissing: (t) => `🧤 ${t} está sem goleiro`,
    spread: (s) => `⚖️ Diferença de OVR entre os times: ${s}`,
    approved: "✅ Times confirmados — já aparecem no app.",
    askPublish: "Publico os times no grupo? (sim/não)",
    byOther: (nick) => `✅ O ${nick} já aprovou os times — tudo certo.`,
    confirmedInApp: "✅ Os times já foram confirmados no app.",
    changedInApp: "Você mexeu nos times no app — mandei a versão do app para você validar.",
    diff: (out, inn) => `🔄 ${out.length ? `Saiu ${list(out)}` : ""}${out.length && inn.length ? " e " : ""}${inn.length ? `entrou ${list(inn)}` : ""} — ajusto os times? (sim/não)`,
    unknownPlayer: (r) => `Não achei "${r}" nos times.`,
    gameLocked: "O jogo já começou ou fechou — não mexo mais nos times.",
  },
};

const EN = {
  welcome: ({ nick, group, formatDesc, others }) => [
    `🧢 Hi ${nick}! I'm your *${NAME.en}* for ${group}.`,
    "From now on I'll handle the behind-the-scenes with you, here in private:",
    "• *Filling the game* — I'll tell you when you're short and, if you want, post a reminder to the group or open spots.",
    "• *Teams* — 24h before kickoff I'll propose balanced teams (with OVR and who plays well together) for you to approve.",
    "• *Matchday* — I keep the night table in your format and send you the recap at the end.",
    "Nothing goes to the group without your \"yes\". Ask me anything: \"who should play in goal?\", \"move the game to Friday 9pm\"…",
    ...(others?.length ? [`You also organise ${list(others)}. I'm focused on *${group}* now — type *group <name>* to switch.`] : []),
    formatDesc
      ? `Your current format is: ${formatDesc}. Want to change anything? (type *format*)`
      : "To start: *what's your game format?*\n1️⃣ Casual — standalone games, no table\n2️⃣ League night — points for win/draw/loss, night table (resets every week)\n3️⃣ Custom — you set everything",
  ].join("\n"),
  notFound: "I couldn't find a group where you're an organiser with this number. Check your phone in the app's Profile (with country code) or use the «Activate the Assistant Coach» button in the group settings.",
  codeInvalid: "This code is no longer valid. Generate a new one in the PITCH app → Group → Settings.",
  chooseGroup: (names) => `You organise several groups:\n${names.map((n, i) => `${i + 1}) ${n}`).join("\n")}\n\nWhich one should I activate? Reply with the number.`,
  chooseGroupAgain: (n) => `Reply with the number (1 to ${n}) or the group name.`,
  switched: (g) => `👍 Now focused on *${g}*.`,
  unknownGroup: (names) => `I couldn't find that group. Your groups: ${list(names)}.`,
  help: "Quick commands: *status* · *table* · *teams* · *format* · *group <name>* · *pause* / *resume* · *yes* / *no* for proposals. Anything else, just write.",
  paused: "⏸️ OK, automatic messages paused. Type *resume* when you want them back.",
  resumed: "▶️ Automatic messages are back on.",
  langSet: "👍 Done.",
  nothingPending: "Nothing is waiting for your confirmation.",
  expired: (id) => `Proposal #${id} has expired.`,
  rejected: (id) => `OK, dropped proposal #${id}.`,
  failedState: "Things changed in the meantime (game, time or teams) — I didn't do anything. Tell me again what you want.",
  dryRun: "(test mode: nothing changed)",
  degraded: (link) => `I've done a lot of thinking today 😅 — until tomorrow I only answer commands: *status*, *table*, *teams*, *yes/no*. Everything else is in the app: ${link}`,
  refusal: "I can't help with that.",
  continuePrompt: "Tell me if you want me to continue.",
  error: "Something went wrong handling that. Try again in a bit.",
  noGame: "There's no game scheduled right now.",
  guardFallback: "I'd rather not risk numbers I haven't checked. Here's what the data says:",
  notManager: "You're no longer an organiser of this group, so I can't do that.",
  ob: {
    type: "What's your game format?\n1️⃣ Casual — standalone games, no table\n2️⃣ League night — night table (resets every week)\n3️⃣ Custom — you set everything",
    teams: "How many teams per night? (2 to 6 · usually 2)",
    playersPerTeam: "Players per team? (usually 5)",
    schedule: "How are games organised?\n1️⃣ Round robin\n2️⃣ Winner stays on\n3️⃣ Fixed number of games\n4️⃣ Add them as we go",
    legs: "Round robin:\n1️⃣ single\n2️⃣ home and away",
    winnerStays: "Winner stays on: max games in a row? (usually 2)",
    fixedGames: "How many games per night?",
    gameMinutes: "How many minutes per game? (usually 10)",
    goalCap: "Goal limit? (e.g. 2 = first to 2 wins · 0 = none)",
    points: "Points for win/draw/loss? (usually 3/1/0)",
    tiebreakers: "Tiebreakers after points? I suggest: goal difference, goals for, head-to-head (reply *ok*).\nOr pick the order: 1 GD · 2 GF · 3 head-to-head · 4 wins · 5 fewest conceded · 6 lots (e.g. \"3 1 2\")",
    playoffs: "Play-off?\n1️⃣ None\n2️⃣ Final between the top 2\n3️⃣ Semi-finals for the top 4\n4️⃣ 1st straight to the final (play-off for the top 3)",
    thirdPlace: "3rd/4th place match? (yes/no)",
    penalties: "Tied play-off games go to penalties? (yes/no)",
    summary: (desc) => `${desc}\nSave it like this? (yes/no)`,
    invalid: "I didn't get that. ",
    hintExit: " (type *exit* to continue later or *restart*)",
    saved: (desc) => `✅ Format saved: ${desc}\nThe app already uses it on Matchday.`,
    restart: "OK, starting over.",
    cancelled: "OK, later then. Type *format* when you want to continue.",
  },
  teams: {
    header: (c, s) => c >= s ? `⚽ Game full (${c}/${s})! Proposed teams:` : `⚽ Proposed teams (${c}/${s} confirmed):`,
    appDraft: "📝 This is the version in the app:",
    footer: "Reply *ok* to confirm, *swap X with Y*, *separate X and Y* or *redraw*.",
    shortAsk: (c, s, when) => `⚽ Game ${when}: ${c}/${s} confirmed. Shall I propose teams with the ${c} confirmed, or wait? (*propose* / *wait*)`,
    waiting: "OK, I'll wait and send the proposal when the game is full.",
    together: (a, b, w, g) => `💡 ${a} and ${b} won ${w} of ${g} games together — split them?`,
    hot: (n) => `🔥 ${n} is in form`,
    gkMissing: (t) => `🧤 ${t} has no goalkeeper`,
    spread: (s) => `⚖️ OVR gap between teams: ${s}`,
    approved: "✅ Teams confirmed — they're in the app now.",
    askPublish: "Shall I post the teams in the group? (yes/no)",
    published: "✅ Posted in the group.",
    notPublished: "OK, not posting.",
    byOther: (nick) => `✅ ${nick} already approved the teams — all sorted.`,
    confirmedInApp: "✅ The teams were already confirmed in the app.",
    changedInApp: "You changed the teams in the app meanwhile — I sent you the app's version to validate.",
    diff: (out, inn) => `🔄 ${out.length ? `${list(out)} dropped out` : ""}${out.length && inn.length ? " and " : ""}${inn.length ? `${list(inn)} came in` : ""} — adjust the teams? (yes/no)`,
    unknownPlayer: (r) => `I couldn't find "${r}" in the teams.`,
    ambiguous: (r, opts) => `"${r}" could be ${list(opts)}. Which one?`,
    gameLocked: "The game has started or closed — I won't touch the teams now.",
  },
  group: {
    quiet: "It's quiet hours in the group (11pm–8am). Try in the morning.",
    noBot: "The bot isn't in this group's WhatsApp chat, so I can't post there.",
    sent: "✅ Sent to the group.",
    already: "That was already sent to the group.",
  },
  done: (what) => `✅ Done: ${what}.`,
  p: {
    status: ({ when, venue, c, s, pending, late, menu = true }) => [
      `📋 Status — ${when}${venue ? ` (${venue})` : ""}`,
      `✅ ${c}/${s} confirmed · *${s - c}* to go`,
      ...(pending.length ? [`⏳ No answer yet: ${list(pending)}`] : []),
      ...(late ? [late] : []),
      ...(menu ? ["Do you want me to:\n1️⃣ post a reminder in the group now, naming who's missing\n2️⃣ open spots to drop-ins (I'll share the invite link)"] : []),
    ].join("\n"),
    lateLine: (rows) => `🐢 Usually confirm late: ${rows.map((r) => `${r.nick} (~${r.h}h before)`).join(", ")}`,
    lateLearning: "🐢 Still learning who confirms late.",
    reminderHint: ({ c, s, at }) => `⏰ ${s - c} still missing. The automatic reminder goes to the group at ${at}.\nWant me to send a stronger one now, with names? (*1*)`,
    gameday: ({ c, s }) => `📅 Game day and still ${s - c} short (${c}/${s}).\n1️⃣ open spots to drop-ins\n2️⃣ reduce spots to ${c}\n3️⃣ cancel the game`,
    spot: ({ nick, c, s }) => `🔓 ${nick ? `${nick} dropped out` : "A spot opened"} — ${s - c} short (${c}/${s}) and no waiting list.\n1️⃣ open spots to drop-ins\n2️⃣ post a reminder in the group`,
    groupStage: ({ table, semis }) => `📊 Group stage done:\n${table}${semis ? `\n🥊 ${semis}` : ""}`,
    summary: ({ header, table, final, top }) => [header, table, final, top, "MVP voting is open in the app."].filter(Boolean).join("\n"),
    unfinished: (link) => `⏱️ The matchday is still open in the app. Forgot to finish it? ${link}`,
    formatNudge: "📐 We haven't set your game format yet. Type *format* and I'll sort it in a minute.",
    prefix: (g) => `[${g}] `,
  },
};

export const TEXTS = { pt: PT, ptbr: PTBR, en: EN };
export const T = (lang) => TEXTS[lang] ?? PT;
